/**
 * AUTO-GENERATED TEST: Create Subobligation
 * Generated by: AI-Driven Testing Agent (MCP Playwright + Filesystem + GitHub)
 * Date: 2026-04-10
 *
 * ═══════════════════════════════════════════════════════════════
 * SELECTOR DISCOVERY RESULTS (from live browser exploration)
 * ═══════════════════════════════════════════════════════════════
 *
 * URL explored: https://cert-comply.content.aws.lexis.com/content-center/subobligationCreation
 *
 * ┌─────────────────────────────────────────────────────────────┐
 * │  insideFrame = true                                         │
 * │  Frame selector: 'iframe.tox-edit-area__iframe'             │
 * │  Total TinyMCE iframes detected: 9                          │
 * │  Playwright API: page.frameLocator('iframe.tox-edit-area__iframe') │
 * └─────────────────────────────────────────────────────────────┘
 *
 * FRAME CONTEXT MAP:
 *   iframe index 0  → AI Assist pane editor     (splitpanes__pane left-side)
 *   iframe index 1  → Description tab           (el-tab-pane, #pane-descriptionDirectional)
 *   iframe index 2  → Compliance Question tab   (el-tab-pane, #pane-descriptionQuestional)
 *   iframe index 3  → Guidance tab              (el-tab-pane, #pane-practicalGuidance)
 *   iframe index 4  → Remedial Action tab       (el-tab-pane, #pane-remedialAction)
 *   iframe index 5  → Consequence tab           (el-tab-pane, #pane-consequence)
 *   iframe index 6  → Compliance Source tab     (el-tab-pane)
 *   iframe index 7  → Definitions tab           (el-tab-pane, #pane-definition)
 *   iframe index 8  → Historical Note tab       (el-tab-pane, #pane-historicalNote)
 *
 * REGULAR SELECTORS (no iframe):
 *   input[placeholder="Select module"]           → Module dropdown
 *   input[placeholder="Select topic"]            → Topic dropdown
 *   input[placeholder="Select obligation"]       → Obligation dropdown
 *   input[placeholder="Enter title"]             → Title field
 *   input[placeholder="Select material type"]    → Material Type dropdown
 *   input[placeholder="Enter frequency"]         → Frequency input
 *   input[placeholder="Enter author"]            → Author input
 *   input[placeholder="Choose submission date"]  → Submission Date picker
 *   input[placeholder="Choose due date"]         → Due Date picker
 *   input[placeholder="Select Jurisdictions"]    → Jurisdictions multi-select
 *   button:has-text("Create")                    → Create button
 *   .el-message, .el-notification               → Toast messages
 *
 * TAB SELECTORS (content editor tabs):
 *   #tab-descriptionDirectional  → Description tab
 *   #tab-descriptionQuestional   → Compliance Question tab
 *   #tab-practicalGuidance       → Guidance tab
 *   #tab-remedialAction          → Remedial Action tab
 *   #tab-consequence             → Consequence tab
 *   #tab-definition              → Definitions tab
 *   #tab-historicalNote          → Historical Note tab
 *   #tab-exerpt                  → Excerpt tab
 *   #tab-metaAi                  → Meta Tags tab
 */

import { test, expect } from '@playwright/test';

// ─── Constants ────────────────────────────────────────────────────────────────
const BASE_URL = 'https://cert-comply.content.aws.lexis.com';
const SSO_URL  = `${BASE_URL}/sso`;

// ─── Helper: fill a TinyMCE editor via frameLocator ───────────────────────────
/**
 * Fills a TinyMCE rich-text editor embedded inside an iframe.
 *
 * insideFrame = true
 * Frame selector: 'iframe.tox-edit-area__iframe'
 *
 * Uses page.frameLocator() to reach inside the iframe, then injects content
 * via the TinyMCE JS API for reliable Vue v-model binding.
 */
async function fillTinyMCEFrame(
  page: any,
  tabSelector: string,
  iframeIndex: number,
  content: string,
  label: string
): Promise<void> {
  // 1. Click the parent tab to make this editor active
  const tab = page.locator(tabSelector).first();
  await tab.click();
  console.log(`  ✓ Clicked ${label} tab`);
  await page.waitForTimeout(1500);

  // 2. Use frameLocator to reach inside the TinyMCE iframe  ← insideFrame=true
  const frame      = page.frameLocator('iframe.tox-edit-area__iframe').nth(iframeIndex);
  const editorBody = frame.locator('body');

  // 3. Click inside the editor body to focus it
  await editorBody.click({ timeout: 8000 }).catch(() => {});
  await page.waitForTimeout(300);

  // 4. Inject content via TinyMCE JS API (most reliable for Vue apps)
  const editorId = await page.evaluate((text: string) => {
    const win = window as any;
    if (!win.tinymce) return null;
    const editor = win.tinymce.activeEditor;
    if (!editor) return null;
    editor.setContent(`<p>${text}</p>`);
    editor.fire('change');
    editor.fire('input');
    editor.fire('keyup');
    return editor.id;
  }, content);

  if (editorId) {
    // Fire blur so Vue v-model picks up the value
    await page.evaluate((id: string) => {
      const win = window as any;
      const editor = win.tinymce?.get(id);
      if (!editor) return;
      editor.save();
      editor.fire('blur');
      editor.fire('focusout');
    }, editorId);
    console.log(`  ✓ ${label} content set via TinyMCE API (id: ${editorId})`);
  } else {
    // Fallback: keyboard typing into the iframe body
    console.log(`  ⚠ TinyMCE API not available – using keyboard fallback for ${label}`);
    await editorBody.click({ timeout: 8000 }).catch(() => {});
    await page.keyboard.press('Control+a');
    await page.keyboard.type(content, { delay: 5 });
    console.log(`  ✓ ${label} typed via keyboard fallback`);
  }

  await page.waitForTimeout(500);
}

// ─── Test Suite ───────────────────────────────────────────────────────────────

test.describe('Content Center – Create Subobligation', () => {

  test('Create Subobligation with Aged Care / Home Care', async ({ page, context }, testInfo) => {

    // Enable full tracing for debugging
    await context.tracing.start({ screenshots: true, snapshots: true, sources: true });
    test.setTimeout(600_000);   // 10 min overall
    page.setDefaultTimeout(30_000);

    // ── STEP 1: Navigate to SSO ──────────────────────────────────────────────
    console.log('\n══════ STEP 1: SSO LOGIN ══════');
    await page.goto(SSO_URL);
    await page.waitForLoadState('networkidle');
    console.log('✓ Navigated to SSO page');

    // ── STEP 2: Developer Login ──────────────────────────────────────────────
    console.log('\n══════ STEP 2: DEVELOPER LOGIN ══════');
    await page.getByRole('button', { name: /Developer Login/i }).click();
    await page.waitForURL('**/content-center**', { timeout: 20_000 });
    console.log('✓ Logged in – redirected to Content Center');
    await page.waitForTimeout(2000);

    // ── STEP 3: Open Subobligation Creation via Create dropdown ─────────────
    console.log('\n══════ STEP 3: OPEN SUBOBLIGATION CREATION ══════');
    await page.getByRole('button', { name: /^Create$/i }).hover();
    await page.waitForTimeout(800);

    // Subobligation opens in a new tab
    const [newPage] = await Promise.all([
      context.waitForEvent('page'),
      page.getByRole('menuitem', { name: /Subobligation/i }).click(),
    ]);

    await newPage.waitForLoadState('networkidle');
    const creationUrl = newPage.url();
    console.log(`✓ Subobligation Creation tab opened: ${creationUrl}`);
    expect(creationUrl).toContain('subobligationCreation');

    const p = newPage;
    p.setDefaultTimeout(30_000);
    await p.waitForTimeout(2000);

    // ── STEP 4: Select Module → Aged Care ───────────────────────────────────
    console.log('\n══════ STEP 4: SELECT MODULE ══════');
    await p.getByRole('textbox', { name: /Select module/i }).click();
    await p.waitForTimeout(800);
    await p.getByRole('listitem').filter({ hasText: /^Aged Care$/ }).click();
    console.log('✓ Module: Aged Care');
    await p.waitForTimeout(500);

    // ── STEP 5: Select Topic → Home Care ────────────────────────────────────
    console.log('\n══════ STEP 5: SELECT TOPIC ══════');
    await p.getByRole('textbox', { name: /Select topic/i }).click();
    await p.waitForTimeout(800);
    await p.getByRole('listitem').filter({ hasText: /^Home Care$/ }).click();
    console.log('✓ Topic: Home Care');
    await p.waitForTimeout(500);

    // ── STEP 6: Select Obligation (first available) ──────────────────────────
    console.log('\n══════ STEP 6: SELECT OBLIGATION ══════');
    await p.getByRole('textbox', { name: /Select obligation/i }).click();
    await p.waitForTimeout(1500);
    // Use .el-select-dropdown__item which is the visible dropdown item class
    const firstObligation = p.locator('.el-select-dropdown:visible li').first();
    await firstObligation.waitFor({ state: 'visible', timeout: 15000 });
    const obligationText  = await firstObligation.textContent();
    await firstObligation.click();
    console.log(`✓ Obligation: ${obligationText?.trim()}`);
    await p.waitForTimeout(500);

    // ── STEP 7: Enter Title ─────────────────────────────────────────────────
    console.log('\n══════ STEP 7: TITLE ══════');
    const timestamp = Date.now();
    const title     = `AI Test Subobligation – ${timestamp}`;
    await p.getByPlaceholder(/Enter title/i).fill(title);
    console.log(`✓ Title: ${title}`);

    // ── STEP 8: Select Material Type ────────────────────────────────────────
    console.log('\n══════ STEP 8: MATERIAL TYPE ══════');
    await p.getByPlaceholder(/Select material type/i).click();
    await p.waitForTimeout(800);
    const materialOption = p.locator('.el-select-dropdown:visible li').first();
    await materialOption.waitFor({ state: 'visible', timeout: 10000 });
    const materialText   = await materialOption.textContent();
    await materialOption.click();
    console.log(`✓ Material Type: ${materialText?.trim()}`);

    // ── STEP 9: Frequency ───────────────────────────────────────────────────
    console.log('\n══════ STEP 9: FREQUENCY ══════');
    await p.getByPlaceholder(/Enter frequency/i).fill('1');
    console.log('✓ Frequency: 1');

    // ── STEP 10: Author ──────────────────────────────────────────────────────
    console.log('\n══════ STEP 10: AUTHOR ══════');
    await p.getByPlaceholder(/Enter author/i).fill('AI Test Agent');
    console.log('✓ Author: AI Test Agent');

    // ── STEP 11: Submission Date ─────────────────────────────────────────────
    console.log('\n══════ STEP 11: SUBMISSION DATE ══════');
    await p.getByPlaceholder(/Choose submission date/i).click();
    await p.waitForTimeout(1500);
    const submissionDay = p
      .locator('.el-picker-panel:visible .el-date-table td.today, .el-picker-panel:visible .el-date-table td.available')
      .first();
    if (await submissionDay.count() > 0) {
      await submissionDay.click();
      console.log('✓ Submission Date selected');
    }
    await p.keyboard.press('Escape');
    await p.waitForTimeout(400);
    await p.locator('body').click({ position: { x: 100, y: 100 } });

    // ── STEP 12: Due Date ────────────────────────────────────────────────────
    console.log('\n══════ STEP 12: DUE DATE ══════');
    await p.getByPlaceholder(/Choose due date/i).click();
    await p.waitForTimeout(1500);
    const dueDay = p
      .locator('.el-picker-panel:visible .el-date-table td.today, .el-picker-panel:visible .el-date-table td.available')
      .first();
    if (await dueDay.count() > 0) {
      await dueDay.click();
      console.log('✓ Due Date selected');
    }
    await p.keyboard.press('Escape');
    await p.waitForTimeout(400);
    await p.locator('body').click({ position: { x: 100, y: 100 } });

    // ── STEP 13: Jurisdictions ───────────────────────────────────────────────
    console.log('\n══════ STEP 13: JURISDICTIONS ══════');
    // The jurisdictions field has a readonly input intercepted by a tag-select input.
    // Click the parent el-select wrapper div instead.
    const jurisdictionsWrapper = p.locator('.el-select').filter({ has: p.locator('input[placeholder*="Jurisdictions" i]') }).first();
    await jurisdictionsWrapper.click();
    await p.waitForTimeout(1500);
    const jurisdictionsList = p.locator('.el-select-dropdown:visible ul');
    const chinaItem  = jurisdictionsList.locator('> div > div').nth(3).locator('span').first();
    const indiaItem  = jurisdictionsList.locator('> div > div').nth(8).locator('span').first();
    await chinaItem.click();
    console.log('✓ Selected: China');
    await p.waitForTimeout(300);
    await indiaItem.click();
    console.log('✓ Selected: India');
    await p.keyboard.press('Escape');
    await p.waitForTimeout(500);

    // ── STEP 14: Create Subobligation ────────────────────────────────────────
    console.log('\n══════ STEP 14: CREATE SUBOBLIGATION ══════');
    await p.locator('button').filter({ hasText: /^Create$/ }).first().click();
    console.log('✓ Clicked Create button');
    await p.waitForTimeout(3000);
    const createToast = p.locator('.el-message, .el-notification').filter({ hasText: /saved successfully/i }).first();
    if (await createToast.count() > 0) {
      console.log(`✓ Toast: "${(await createToast.textContent())?.trim()}"`);
    }

    // ── STEP 15: Fill Content Tabs using frameLocator (insideFrame=true) ─────
    console.log('\n══════ STEP 15: FILL CONTENT TABS (frameLocator – insideFrame=true) ══════');
    console.log('  Frame selector: iframe.tox-edit-area__iframe');

    const descriptionContent = 'Subobligation description: aged care providers must establish compliance programs for home care service delivery. Documentation requirements include policies, procedures, and training records. Regular audits are mandatory.';
    const complianceContent  = 'Compliance question: Do aged care home care providers have documented evidence of compliance with all applicable regulatory requirements, including staff training records and incident management procedures?';
    const guidanceContent    = 'Guidance: Providers should implement systematic approaches to compliance management including regular internal audits, staff training programs, and documented evidence collection processes.';
    const remedialContent    = 'Remedial action: Upon identification of non-compliance, providers must immediately notify the regulator, implement corrective measures, document all actions taken, and monitor effectiveness.';

    // Fill in reverse order so Description is the last active tab when we save
    await fillTinyMCEFrame(p, '#tab-remedialAction',        4, remedialContent,    'Remedial Action');
    await fillTinyMCEFrame(p, '#tab-practicalGuidance',     3, guidanceContent,     'Guidance');
    await fillTinyMCEFrame(p, '#tab-descriptionQuestional', 2, complianceContent,   'Compliance Question');
    await fillTinyMCEFrame(p, '#tab-descriptionDirectional',1, descriptionContent,  'Description'); // LAST

    console.log('  ✓ All content tabs filled using frameLocator (insideFrame=true)');

    // ── STEP 16: Save as Draft ────────────────────────────────────────────────
    console.log('\n══════ STEP 16: SAVE AS DRAFT ══════');
    const saveBtn = p.locator('div.form-section button.el-button--primary').first();
    await saveBtn.scrollIntoViewIfNeeded();
    await saveBtn.click();
    console.log('✓ Clicked Save as Draft');
    await p.waitForTimeout(4000);

    const draftToast = p.locator('.el-message, .el-notification').filter({ hasText: /saved successfully/i }).first();
    if (await draftToast.count() > 0) {
      console.log(`✓ Saved – Toast: "${(await draftToast.textContent())?.trim()}"`);
    } else {
      console.log('⚠ Save toast not found (may have faded)');
    }

    // ── STEP 17: Publish ──────────────────────────────────────────────────────
    console.log('\n══════ STEP 17: PUBLISH ══════');
    const publishBtn = p.locator('button').filter({ hasText: /^Publish$/ }).first();
    const publishEnabled = await publishBtn.isEnabled().catch(() => false);

    if (!publishEnabled) {
      console.log('⚠ Publish button disabled – subobligation saved as draft (acceptable)');
    } else {
      await publishBtn.scrollIntoViewIfNeeded();
      await publishBtn.click();
      console.log('✓ Clicked Publish');
      await p.waitForTimeout(3000);

      const confirmBtn = p.locator('button').filter({ hasText: /Yes.*Publish|Confirm/i }).first();
      if (await confirmBtn.count() > 0) {
        await confirmBtn.click();
        console.log('✓ Confirmed publish dialog');
        await p.waitForTimeout(5000);
      }

      const publishToast = p
        .locator('.el-message, .el-notification')
        .filter({ hasText: /published successfully/i })
        .first();
      if (await publishToast.count() > 0) {
        const msg = (await publishToast.textContent())?.trim();
        console.log(`✅ Published – "${msg}"`);
        await expect(publishToast).toBeVisible({ timeout: 10_000 });
      }
    }

    // ── STEP 18: Final screenshot & trace ─────────────────────────────────────
    await p.screenshot({ path: testInfo.outputPath('final-state.png') });
    await context.tracing.stop({ path: testInfo.outputPath('trace.zip') }).catch(() => {});
    console.log('\n🎉 TEST COMPLETED – Create Subobligation (Aged Care / Home Care)');
    console.log('   insideFrame=true | frameLocator: iframe.tox-edit-area__iframe');

    if (!p.isClosed()) await p.close();
  });
});
